diff --git a/oblivion-wars-godot/Scenes/Levels/MainLevel.tscn b/oblivion-wars-godot/Scenes/Levels/MainLevel.tscn
index 27e4031..1454097 100644
--- a/oblivion-wars-godot/Scenes/Levels/MainLevel.tscn
+++ b/oblivion-wars-godot/Scenes/Levels/MainLevel.tscn
@@ -4,7 +4,7 @@
 [ext_resource type="PackedScene" uid="uid://cb4iahq5chr65" path="res://Scenes/Characters/PlayerCharacterBody2D.tscn" id="2_jxtak"]
 [ext_resource type="PackedScene" uid="uid://ceq74t0uxq1ed" path="res://Scenes/UI/crosshair.tscn" id="3_jxtak"]
 [ext_resource type="Script" uid="uid://b2dl33mekocnv" path="res://Scripts/Camera/CameraController.cs" id="4_camera"]
-[ext_resource type="TileSet" uid="uid://cifh4slrp6lmq" path="res://Resources/Tilemaps/kenney_abstract-platformer/Godot/KenneyAbstractPlatformer-TileSet.tres" id="5_rqyoi"]
+[ext_resource type="TileSet" uid="uid://bcshhvut4q14s" path="res://Resources/Tilemaps/kenney_abstract-platformer/Godot/KenneyAbstract-Half.tres" id="4_sx5r3"]
 [ext_resource type="Script" uid="uid://b3dp1tcocrav0" path="res://Scripts/UI/DebugHUD.cs" id="6_debughud"]
 [ext_resource type="PackedScene" uid="uid://cygwcj2tkmvgn" path="res://Scenes/Characters/TargetDummy.tscn" id="7_sx5r3"]
 
@@ -28,6 +28,8 @@ _bodyFlipDelay = 0.3
 script = ExtResource("4_camera")
 _target = NodePath("../CharacterController/PlayerCharacterBody2D")
 _camera = NodePath("Camera2D")
+_followOffset = Vector2(0, -250)
+_deadzone = Vector2(40, 50)
 _rotationSpeed = 7.0
 _minRotationSpeed = 2.0
 _rotationDelay = 0.0
@@ -37,8 +39,8 @@ ignore_rotation = false
 
 [node name="TileMapLayer1" type="TileMapLayer" parent="Control" unique_id=77805476]
 position = Vector2(-1, -1)
-tile_map_data = PackedByteArray("AAACAAYAAAAFAAUAAAADAAYAAAAGAAUAAAAEAAYAAAAFAAUAAAAFAAYAAAAGAAUAAAAGAAYAAAAFAAUAAAAHAAYAAAAGAAUAAAAIAAYAAAAFAAUAAAAJAAYAAAAGAAUAAAAKAAYAAAAFAAUAAAALAAYAAAAGAAUAAAAMAAYAAAAFAAUAAAANAAYAAAACAAMAAAABAAYAAAABAAMAAAABAAUAAAACAAMAAFABAAQAAAACAAMAAFABAAMAAAACAAMAAFABAAIAAAACAAMAAFABAAEAAAACAAMAAFABAAAAAAACAAMAAFABAP//AAACAAMAAFABAP7/AAACAAMAAFABAP3/AAACAAMAAFAJAP//AAAHAAQAAAAKAP//AAAIAAQAAAABAPf/AAABAAMAACABAPz/AAACAAMAAFABAPv/AAACAAMAAFABAPr/AAACAAMAAFABAPn/AAACAAMAAFABAPj/AAACAAMAAFACAAUAAAAMAAkAAAADAAUAAAAMAAkAAAAOAAYAAAACAAMAAAAPAAYAAAACAAMAAAAQAAYAAAACAAMAAAARAAYAAAACAAMAAAASAAYAAAACAAMAAAATAAYAAAACAAMAAAAUAAYAAAACAAMAAAAVAAYAAAACAAMAAAAWAAYAAAACAAMAAAAXAAYAAAACAAMAAAAYAAYAAAACAAMAAAAZAAYAAAACAAMAAAAaAAYAAAACAAMAAAAbAAYAAAACAAMAAAAcAAYAAAACAAMAAAAdAAYAAAACAAMAAAAeAAYAAAACAAMAAAAfAAYAAAACAAMAAAAgAAYAAAACAAMAAAAhAAYAAAACAAMAAAAiAAYAAAACAAMAAAAjAAYAAAACAAMAAAAkAAYAAAACAAMAAAAlAAYAAAACAAMAAAABAPT/AAAFAAUAAAAeAPT/AAAFAAUAAAAdAPT/AAAFAAUAAAAcAPT/AAAFAAUAAAAbAPT/AAAFAAUAAAAaAPT/AAAFAAUAAAAZAPT/AAAFAAUAAAAYAPT/AAAFAAUAAAAXAPT/AAAFAAUAAAAWAPT/AAAFAAUAAAAVAPT/AAAFAAUAAAAUAPT/AAAFAAUAAAATAPT/AAAFAAUAAAASAPT/AAAFAAUAAAARAPT/AAAFAAUAAAAQAPT/AAAFAAUAAAAPAPT/AAAFAAUAAAAOAPT/AAAFAAUAAAANAPT/AAAFAAUAAAAMAPT/AAAFAAUAAAALAPT/AAAFAAUAAAAKAPT/AAAFAAUAAAAJAPT/AAAFAAUAAAAIAPT/AAAFAAUAAAAHAPT/AAAFAAUAAAAGAPT/AAAFAAUAAAAFAPT/AAAFAAUAAAAEAPT/AAAFAAUAAAADAPT/AAAFAAUAAAACAPT/AAAFAAUAAAALAAUAAAAGAAMAAAARAAUAAAAGAAMAAAARAAQAAAAGAAMAAAAXAAUAAAAGAAMAAAAXAAQAAAAGAAMAAAAXAAMAAAAGAAMAAAAFAAUAAAAGAAMAAAAFAAQAAAAGAAMAAAAFAAMAAAAGAAMAAAA=")
-tile_set = ExtResource("5_rqyoi")
+tile_map_data = PackedByteArray("AAAMAPr/AAAFAAQAAAAMAP3/AAAFAAQAAAAMAP7/AAAFAAQAAAAMAP//AAAFAAQAAAAMAAAAAAAFAAQAAAAMAAEAAAAFAAQAAAAMAAIAAAAFAAQAAAAMAAMAAAAFAAQAAAAMAAQAAAAFAAQAAAAMAAUAAAAFAAQAAAAMAAYAAAAFAAQAAAAMAAcAAAAFAAQAAAAMAAgAAAAFAAQAAAAMAAkAAAAFAAQAAAAMAAoAAAAFAAQAAAAMAAsAAAAFAAQAAAAMAAwAAAAFAAQAAAANAPr/AAAFAAUAAAANAAsAAAAMAAkAAAANAAwAAAAFAAUAAAAOAPr/AAAFAAUAAAAOAAsAAAAMAAkAAAAOAAwAAAAGAAUAAAAPAPr/AAAFAAUAAAAPAAwAAAAFAAUAAAAQAPr/AAAFAAUAAAAQAAkAAAAGAAMAAAAQAAoAAAAGAAMAAAAQAAsAAAAGAAMAAAAQAAwAAAAGAAUAAAARAPr/AAAFAAUAAAARAAwAAAAFAAUAAAASAPr/AAAFAAUAAAASAAwAAAAGAAUAAAATAPr/AAAFAAUAAAATAAwAAAAFAAUAAAAUAPr/AAAFAAUAAAAUAAwAAAAGAAUAAAAVAPr/AAAFAAUAAAAVAAwAAAAFAAUAAAAWAPr/AAAFAAUAAAAWAAsAAAAGAAMAAAAWAAwAAAAGAAUAAAAXAPr/AAAFAAUAAAAXAAwAAAAFAAUAAAAYAPr/AAAFAAUAAAAYAAwAAAACAAMAAAAZAPr/AAAFAAUAAAAZAAwAAAACAAMAAAAaAPr/AAAFAAUAAAAaAAwAAAACAAMAAAAbAPr/AAAFAAUAAAAbAAwAAAACAAMAAAAcAPr/AAAFAAUAAAAcAAoAAAAGAAMAAAAcAAsAAAAGAAMAAAAcAAwAAAACAAMAAAAdAPr/AAAFAAUAAAAdAAwAAAACAAMAAAAeAPr/AAAFAAUAAAAeAAwAAAACAAMAAAAfAPr/AAAFAAUAAAAfAAwAAAACAAMAAAAgAPr/AAAFAAUAAAAgAAwAAAACAAMAAAAhAPr/AAAFAAUAAAAhAAwAAAACAAMAAAAiAPr/AAAFAAUAAAAiAAkAAAAGAAMAAAAiAAoAAAAGAAMAAAAiAAsAAAAGAAMAAAAiAAwAAAACAAMAAAAjAPr/AAAFAAUAAAAjAAwAAAACAAMAAAAkAPr/AAAFAAUAAAAkAAwAAAACAAMAAAAlAPr/AAAFAAUAAAAlAAwAAAACAAMAAAAmAPr/AAAFAAUAAAAmAAwAAAACAAMAAAAnAPr/AAAFAAUAAAAnAAwAAAACAAMAAAAoAPr/AAAFAAUAAAAoAAwAAAACAAMAAAApAPr/AAAFAAUAAAApAAwAAAACAAMAAAAqAAwAAAACAAMAAAArAAwAAAACAAMAAAAsAAwAAAACAAMAAAAtAAwAAAACAAMAAAAuAAwAAAACAAMAAAAvAAwAAAACAAMAAAAwAAwAAAACAAMAAAAPAAIAAAAHAAQAAAAQAAIAAAAIAAQAAAAqAPr/AAAFAAQAAAAqAAsAAAAFAAQAAAAqAAoAAAAFAAQAAAAqAAkAAAAFAAQAAAAqAAgAAAAFAAQAAAAqAAcAAAAFAAQAAAAqAAYAAAAFAAQAAAAqAAUAAAAFAAQAAAAqAAQAAAAFAAQAAAAqAAMAAAAFAAQAAAAqAAIAAAAFAAQAAAAqAAEAAAAFAAQAAAAqAAAAAAAFAAQAAAAqAP//AAAFAAQAAAAqAP7/AAAFAAQAAAAqAP3/AAAFAAQAAAAqAPz/AAAFAAQAAAAqAPv/AAAFAAQAAAAMAPz/AAAFAAQAAAAMAPv/AAAFAAQAAAA=")
+tile_set = ExtResource("4_sx5r3")
 
 [node name="UI" type="CanvasLayer" parent="." unique_id=1326346317]
 
